// Auto-generated by: supabase gen types typescript --project-id <your-project-id>
// Run: pnpm --filter @punchcard/supabase gen:types
// This file should be regenerated after every migration.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          mobile_number: string
          first_name: string | null
          last_name: string | null
          birthday: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          mobile_number: string
          first_name?: string | null
          last_name?: string | null
          birthday?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          mobile_number?: string
          first_name?: string | null
          last_name?: string | null
          birthday?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      businesses: {
        Row: {
          id: string
          name: string
          contact_email: string | null
          contact_phone: string | null
          address: string | null
          logo_url: string | null
          trial_start_date: string | null
          trial_end_date: string | null
          subscription_status: string
          forever_free: boolean
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          contact_email?: string | null
          contact_phone?: string | null
          address?: string | null
          logo_url?: string | null
          trial_start_date?: string | null
          trial_end_date?: string | null
          subscription_status?: string
          forever_free?: boolean
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          contact_email?: string | null
          contact_phone?: string | null
          address?: string | null
          logo_url?: string | null
          trial_start_date?: string | null
          trial_end_date?: string | null
          subscription_status?: string
          forever_free?: boolean
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      business_users: {
        Row: {
          id: string
          business_id: string
          user_id: string
          role: string
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          business_id: string
          user_id: string
          role: string
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          user_id?: string
          role?: string
          is_active?: boolean
          created_at?: string
        }
      }
      outlets: {
        Row: {
          id: string
          business_id: string
          name: string
          address: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          name: string
          address?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          name?: string
          address?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      loyalty_cards: {
        Row: {
          id: string
          business_id: string
          name: string
          description: string | null
          image_url: string | null
          stamps_required: number
          reward_title: string
          reward_description: string | null
          max_stamps_per_visit: number
          collect_bill_value: boolean
          terms_and_conditions: string | null
          is_active: boolean
          start_date: string | null
          end_date: string | null
          outlet_scope: string
          redemption_scope: string
          auto_renew: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          name: string
          description?: string | null
          image_url?: string | null
          stamps_required: number
          reward_title: string
          reward_description?: string | null
          max_stamps_per_visit?: number
          collect_bill_value?: boolean
          terms_and_conditions?: string | null
          is_active?: boolean
          start_date?: string | null
          end_date?: string | null
          outlet_scope?: string
          redemption_scope?: string
          auto_renew?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          name?: string
          description?: string | null
          image_url?: string | null
          stamps_required?: number
          reward_title?: string
          reward_description?: string | null
          max_stamps_per_visit?: number
          collect_bill_value?: boolean
          terms_and_conditions?: string | null
          is_active?: boolean
          start_date?: string | null
          end_date?: string | null
          outlet_scope?: string
          redemption_scope?: string
          auto_renew?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      customer_cards: {
        Row: {
          id: string
          user_id: string
          loyalty_card_id: string
          business_id: string
          stamps_collected: number
          status: string
          cycle_number: number
          issued_at: string
          completed_at: string | null
          redeemed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          loyalty_card_id: string
          business_id: string
          stamps_collected?: number
          status?: string
          cycle_number?: number
          issued_at?: string
          completed_at?: string | null
          redeemed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          loyalty_card_id?: string
          business_id?: string
          stamps_collected?: number
          status?: string
          cycle_number?: number
          issued_at?: string
          completed_at?: string | null
          redeemed_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      transactions: {
        Row: {
          id: string
          business_id: string
          outlet_id: string | null
          loyalty_card_id: string
          customer_card_id: string
          user_id: string
          staff_business_user_id: string
          transaction_type: string
          quantity: number
          bill_value: number | null
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          business_id: string
          outlet_id?: string | null
          loyalty_card_id: string
          customer_card_id: string
          user_id: string
          staff_business_user_id: string
          transaction_type: string
          quantity?: number
          bill_value?: number | null
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          outlet_id?: string | null
          loyalty_card_id?: string
          customer_card_id?: string
          user_id?: string
          staff_business_user_id?: string
          transaction_type?: string
          quantity?: number
          bill_value?: number | null
          notes?: string | null
          created_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
